<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Australia</name>
   <tag></tag>
   <elementGuidId>926d583a-5ad2-4e59-9d56-903d1f6cad4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.navFooterLine.navFooterLinkLine.navFooterPadItemLine > ul > li.nav_first > a.nav_a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navFooter']/div[4]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9569e646-f4e5-47b5-b77d-64fe3a6636c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.com.au/ref=footer_au</value>
      <webElementGuid>07e2656a-eb60-4b1f-a22f-bd7ff8c9f1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav_a</value>
      <webElementGuid>d09315b7-0fc6-4783-9fd3-9aa7a30ee278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Australia</value>
      <webElementGuid>bb8d1d5a-40ec-4125-96d4-30fec14587cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navFooter&quot;)/div[@class=&quot;navFooterLine navFooterLinkLine navFooterPadItemLine&quot;]/ul[1]/li[@class=&quot;nav_first&quot;]/a[@class=&quot;nav_a&quot;]</value>
      <webElementGuid>af9bf0d0-0e50-4ec4-9711-1fcd482aa5a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navFooter']/div[4]/ul/li/a</value>
      <webElementGuid>c4157879-d82c-43b5-a350-9b6b8789233d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Australia')]</value>
      <webElementGuid>e1b1f142-b722-4c0e-9b05-ccdf58a34c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::a[1]</value>
      <webElementGuid>f52f1df8-6a19-46ca-bfb6-cd15b53dbbcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::a[3]</value>
      <webElementGuid>05009a5b-604b-4abb-bbbe-430467af38b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brazil'])[1]/preceding::a[1]</value>
      <webElementGuid>8b517371-0fbf-481a-99f6-85da6c2007b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Canada'])[1]/preceding::a[2]</value>
      <webElementGuid>eb46ab7f-134a-4892-9b09-3d8cf4c8281c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Australia']/parent::*</value>
      <webElementGuid>bf53f290-10b6-4e23-9f65-69d43606769b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.com.au/ref=footer_au')]</value>
      <webElementGuid>4f8cb271-167c-404b-b747-ef910a9917f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li/a</value>
      <webElementGuid>3de72353-3b39-4857-9434-9f9141cffddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.amazon.com.au/ref=footer_au' and (text() = 'Australia' or . = 'Australia')]</value>
      <webElementGuid>c1fcc2e0-f8f5-4bbb-a27d-809e2bf3e37e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
